# Generated by Django 6.0.6 on 2026-07-02 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='título')),
                ('destino', models.CharField(max_length=120, verbose_name='destino')),
                ('data_inicio', models.DateField(verbose_name='data de início')),
                ('data_fim', models.DateField(verbose_name='data de fim')),
                ('publica', models.BooleanField(default=False, verbose_name='pública')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'viagem',
                'verbose_name_plural': 'viagens',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('data_hora', models.DateTimeField(verbose_name='data e hora')),
                ('custo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='custo estimado')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividades', to='travels.categoria', verbose_name='categoria')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='travels.viagem', verbose_name='viagem')),
            ],
            options={
                'verbose_name': 'atividade',
                'verbose_name_plural': 'atividades',
                'ordering': ['data_hora'],
            },
        ),
    ]
