# Generated by Django 6.0.6 on 2026-07-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='viagens/%Y/%m/', verbose_name='foto de capa'),
        ),
    ]
